### PR TITLE
Name refactoring, duplication rule, --dump.

### PR DESCRIPTION
**Pull request by Josef-Vonasek**
This pull request has two parts:

First I polished the function names a little bit, so the code is easier to read (IMHO putting `get` or `function argument names` inside function name is antipattern). Although descriptive function names can lead to better readability, not being concise will lead to the opposite.

Secondly, I cleaned up the duplication rule and reused the `A` and `B` nodes, so there is only one allocation instead of two. Running `main.lam` is almost twice as fast with this change!

### CODE REVIEW

**Comment by Josef-Vonasek** [comment]
I have added `--dump` option to dump the memory of reduced interaction net.

**Comment by MaiaVictor** [comment]
Uh, I missed this again, sorry. :(

**Comment by MaiaVictor** [comment]
Nope, did you use this number? https://onetimesecret.com/secret/dre5ffl9ygb59h88ck8wlbwr8myram5

**Comment by MaiaVictor** [comment]
Just thinking, when an annihilation rule is activated and one of the neighbor nodes has kind 0, it would probably be safe to add all nodes then connected to era node to the reuse array, no? That may improve performance further...

**Comment by MaiaVictor** [comment]
By the way, you may be interested in this: https://gist.github.com/MaiaVictor/130b7a42d708923d0f89e07e226b61ad

I've managed to hit 20m rewrites/s with this implementation.

**Comment by Josef-Vonasek** [comment]
Ha. Nice. I have been thinking about rust implementation just the other day.

Note that Vec<Node> will be just as fast as using Vec<ui32>, but it will definitely improve the code readability. 

2. 5. 2018 11:30 PM, 11:30 PM, MaiaVictor <notifications@github.com> napsal/a:

**Comment by Josef-Vonasek** [comment]
IMO to be compete with other languages we need around 10 billions rewrites per second.

Modern CPUs can process up to ~100 billions instructions per second so we definitely don't want to be slower by a factor of 100.

But that's only on paper so It would be nice to have some real benchmarks e.g. basic list operations haskell vs inets . 

2. 5. 2018 11:30 PM, 11:30 PM, MaiaVictor <notifications@github.com> napsal/a:

**Comment by Josef-Vonasek** [comment]
Given how simple the algorithm is, it should be pretty easy to rewrite it directly in assembly or llvm. 

2. 5. 2018 11:30 PM, 11:30 PM, MaiaVictor <notifications@github.com> napsal/a:

**Pull request merged**
